name: Update Gold Watchlist

on:
  schedule:
    - cron: "30 9 * * *"   # Runs daily at 08:30 AM IST (03:00 UTC)
  workflow_dispatch:      # Allows you to run it manually too

permissions:
  contents: write         # Allow workflow to push changes to repo

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pandas requests

      - name: Run script
        run: python gold_watchlist.py ${{ secrets.GOLD_API_KEY }} ${{ secrets.USD_INR_API }}
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add gold_watchlist.csv
          git commit -m "Auto update gold watchlist" || echo "No changes to commit"
          git push https://x-oauth-basic:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git main
